# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

@fibs = [1, 2]
@previous = 1
@current = 2

def generate_fibs(previous, current)
  @fibs << previous + current
  @previous, @current = current, @fibs.last
end

while @current < 4000000
  generate_fibs(@previous, @current)
end

@fibs.pop
@fibs.delete_if { |fib| fib.odd? }
puts "The sum of the even-valued terms below 4 million in the Fibonacci sequence is #{@fibs.inject(:+)}."
